apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
    - name: busybox
      image: busybox
      command: ["sh", "-c", "while true; do echo busybox running; sleep 30; done"]