log:
  level: DEBUG

api:
  dashboard: true
  insecure: true  # 內部開發用，正式環境請使用 TLS

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: your@email.com
      storage: /letsencrypt/acme.json
      tlsChallenge: true
